name: tf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=2.0.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.7.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-python=1.1.0
  - c-ares=1.23.0
  - ca-certificates=2023.08.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.1.2
  - contourpy=1.2.0
  - cryptography=41.0.3
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - flatbuffers=23.5.26
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gast=0.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.24.0
  - google-auth-oauthlib=0.5.3
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.9.0
  - hdf5=1.14.0
  - icu=58.2
  - idna=3.6
  - importlib-metadata=6.9.0
  - importlib_resources=6.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.9
  - keras=2.12.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20211102.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.2.1
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown=3.5.1
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.23.5
  - oauthlib=3.2.2
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=23.5.26
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qtconsole=5.5.0
  - qtpy=2.4.1
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rsa=4.9
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.44.2
  - stack_data=0.2.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.12.0
  - tensorflow-base=2.12.0
  - tensorflow-estimator=2.12.0
  - termcolor=2.3.0
  - terminado=0.17.1
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=2.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - arrow==1.3.0
    - fqdn==1.5.1
    - isoduration==20.11.0
    - jsonpointer==2.4
    - kaleido==0.2.1
    - keras-tuner==1.4.6
    - plotly==5.18.0
    - seaborn==0.13.0
    - tenacity==8.2.3
    - types-python-dateutil==2.8.19.14
    - uri-template==1.3.0
    - webcolors==1.13
    - wrapt==1.14.1
